import mongoose from "mongoose";

/**
 * IssuedToken — Registry of tokens actually generated by this system.
 *
 * Every token minted by authController (login) is recorded here.
 * detectForgery in detectionEngine.js checks that any token arriving
 * at a protected endpoint exists in this registry.
 *
 * A token NOT in this registry but passing jwt.verify() means the
 * attacker knows the secret key and forged it externally (algorithm
 * confusion, weak key brute-force, etc.) — Rule 25 of the paper.
 *
 * TTL: entries expire after 24 hours (longer than any token lifetime)
 * so the collection never grows unbounded.
 */

const issuedTokenSchema = new mongoose.Schema(
  {
    tokenHash: { type: String, required: true, unique: true },
    userId:    { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    issuedAt:  { type: Date, default: Date.now },
  },
  { timestamps: false }
);

// Auto-delete after 24 hours
issuedTokenSchema.index({ issuedAt: 1 }, { expireAfterSeconds: 86400 });

export default mongoose.model("IssuedToken", issuedTokenSchema);
