/**
 * Detection Engine — Signature Rules + ML Augmentation
 *
 * Rules: unchanged in count/category. Thresholds tuned where the paper's
 *        81.4% accuracy baseline suggests conservative changes.
 * ML:    Isolation Forest anomaly score is consumed here as an additional
 *        signal. It never replaces a rule — it adds a continuous anomaly
 *        dimension that signature rules cannot express (e.g. a request
 *        whose individual features are all "normal" but whose combination
 *        is highly unusual).
 */

import Alert       from "../models/Alert.js";
import RequestLog  from "../models/RequestLog.js";
import RevokedToken from "../models/RevokedToken.js";
import IssuedToken  from "../models/IssuedToken.js";

import { getUserBaseline }  from "./userBehavior.js";
import { updateRiskScore }  from "./riskEngine.js";
import { geoDistance }      from "./userEnvironment.js";
import { scoreRequest }     from "./isolationForest.js";

/* ------------------------------------------------ */
/* REQUEST ARRIVAL TIME — module-level              */
/* Set by runSecurityChecks before each run.        */
/* Safe: Node.js is single-threaded; setImmediate   */
/* callbacks never interleave.                      */
/* ------------------------------------------------ */

let _currentRequestArrivalTime = null;

/* ------------------------------------------------ */
/* ALERT CREATION                                   */
/* ------------------------------------------------ */

const createAlert = async ({
  userId,
  tokenHash,
  type,
  severity,
  reason,
  actionTaken = "NONE",
  mlScore = null,           // attach ML score when alert is ML-assisted
}) => {

  if (!tokenHash) {
    console.warn("Skipping alert: tokenHash missing for", type);
    return;
  }

  // Dedup window: 30s for high-frequency, 120s for the rest
  const dedupWindow = ["RATE_ANOMALY", "BEHAVIOR_ANOMALY", "INVALID_TOKEN_FLOOD"].includes(type)
    ? 30000
    : 120000;

  const exists = await Alert.findOne({
    tokenHash,
    type,
    isResolved: false,
    createdAt: { $gte: new Date(Date.now() - dedupWindow) }
  });

  if (!exists) {
    const reasonFull = mlScore !== null
      ? `${reason} [ML anomaly score: ${mlScore.toFixed(3)}]`
      : reason;

    const detectionLatencyMs = _currentRequestArrivalTime ? Date.now() - _currentRequestArrivalTime : null;
    await Alert.create({ userId, tokenHash, type, severity, reason: reasonFull, actionTaken, detectionLatencyMs });
    await updateRiskScore(userId, tokenHash, type);
    console.log(`🚨 ALERT [${severity}]: ${type} — ${reasonFull}${detectionLatencyMs !== null ? ` (detected in ${detectionLatencyMs}ms)` : ""}`);
  }

};

/* ------------------------------------------------ */
/* ML-BASED ANOMALY DETECTION                       */
/*                                                  */
/* Uses the Isolation Forest to score the current   */
/* request against live traffic history. No rules   */
/* added — this consumes the continuous IF score    */
/* and translates it into the existing alert/risk   */
/* framework only when confidence is high.          */
/*                                                  */
/* Threshold 0.72 is conservative (paper favours    */
/* low false-negative rate over low false-positive).*/
/* Threshold 0.85 = CRITICAL (very high confidence).*/
/* ------------------------------------------------ */

export const detectMLAnomaly = async ({ userId, tokenHash, ipAddress, userAgent }) => {

  if (!userId || !tokenHash) return;

  const { score, vector } = await scoreRequest({ userId, tokenHash, ipAddress, userAgent });

  if (score >= 0.85) {
    await createAlert({
      userId,
      tokenHash,
      type: "BEHAVIOR_ANOMALY",
      severity: "CRITICAL",
      reason: `Isolation Forest: highly anomalous request profile (features: reqRate=${vector?.[0]}, endpoints=${vector?.[1]}, hour=${vector?.[2]}, ipChange=${vector?.[3]}, uaChange=${vector?.[4]}, tokenAgeMin=${vector?.[5]?.toFixed(0)})`,
      mlScore: score,
    });
  } else if (score >= 0.72) {
    await createAlert({
      userId,
      tokenHash,
      type: "BEHAVIOR_ANOMALY",
      severity: "HIGH",
      reason: `Isolation Forest: anomalous request profile. Feature vector: [${vector?.map(v => Number(v).toFixed(1)).join(", ")}]`,
      mlScore: score,
    });
  }
  // 0.5–0.72: indeterminate — no alert, but the score still feeds the
  // risk engine indirectly through the BEHAVIOR_ANOMALY alert path.

};

/* ------------------------------------------------ */
/* RULE 25 — FORGED / UNISSUED TOKEN                */
/*                                                  */
/* Paper Group 8: Token not generated by this       */
/* system's auth or refresh API → CRITICAL.         */
/* Implemented via IssuedToken registry.            */
/* ------------------------------------------------ */

export const detectForgery = async ({ userId, tokenHash }) => {

  if (!tokenHash) return;

  const issued = await IssuedToken.findOne({ tokenHash });

  if (!issued) {
    await createAlert({
      userId,
      tokenHash,
      type: "FORGED_TOKEN",
      severity: "CRITICAL",
      reason: "Token not found in issuance registry — possible forgery, algorithm confusion, or key compromise",
      actionTaken: "REVOKED",
    });

    // Immediately revoke — unrecognised token must not remain valid
    await RevokedToken.updateOne(
      { tokenHash },
      { $setOnInsert: { tokenHash, reason: "Forged/unissued token — Rule 25" } },
      { upsert: true }
    );
  }

};

/* ------------------------------------------------ */
/* TOKEN REPLAY DETECTION                           */
/* Window: 5 min. Severity: CRITICAL + auto-revoke  */
/* Paper Group 3 (Rules 7–12)                       */
/* ------------------------------------------------ */

export const detectTokenReplay = async ({ userId, tokenHash }) => {

  const logs = await RequestLog.find({
    tokenHash,
    createdAt: { $gte: new Date(Date.now() - 300000) }   // 5-min window
  }).select("ipAddress userAgent").lean();

  const uniqueIPs = new Set(logs.map(l => l.ipAddress));
  const uniqueUAs = new Set(logs.map(l => l.userAgent));

  // Same token, multiple IPs AND UAs simultaneously — Rule 11 (Critical)
  if (uniqueIPs.size > 1 && uniqueUAs.size > 1) {
    await createAlert({
      userId, tokenHash,
      type: "TOKEN_REPLAY",
      severity: "CRITICAL",
      reason: `Same token from ${uniqueIPs.size} IPs and ${uniqueUAs.size} user-agents in 5 min`,
      actionTaken: "REVOKED",
    });
  } else if (uniqueIPs.size > 1) {
    // Multiple IPs only — Rule 7/8
    await createAlert({
      userId, tokenHash,
      type: "TOKEN_REPLAY",
      severity: "CRITICAL",
      reason: `Same token used from ${uniqueIPs.size} distinct IPs: ${[...uniqueIPs].join(", ")}`,
      actionTaken: "REVOKED",
    });
  } else if (uniqueUAs.size > 1) {
    // Multiple UAs only — Rule 9/10
    await createAlert({
      userId, tokenHash,
      type: "TOKEN_REPLAY",
      severity: "HIGH",
      reason: `Same token used from ${uniqueUAs.size} distinct user-agents in 5 min`,
    });
  }

  if (uniqueIPs.size > 1) {
    await RevokedToken.updateOne(
      { tokenHash },
      { $setOnInsert: { tokenHash, reason: "Token replay detected — immediate revocation" } },
      { upsert: true }
    );
  }

};

/* ------------------------------------------------ */
/* RATE ANOMALY                                     */
/* Tiered: >10x = CRITICAL, >4x = HIGH             */
/* Floor avgRate = 5 prevents new-user FPs          */
/* ------------------------------------------------ */

export const detectRateAnomaly = async ({ userId, tokenHash }) => {

  const baseline  = await getUserBaseline(userId);
  const avgRate   = Math.max(baseline?.avgRate || 1, 5);

  const count = await RequestLog.countDocuments({
    userId,
    createdAt: { $gte: new Date(Date.now() - 10000) }
  });

  const deviation = count / avgRate;

  if (deviation > 10) {
    await createAlert({
      userId, tokenHash,
      type: "RATE_ANOMALY",
      severity: "CRITICAL",
      reason: `Extreme spike: ${count} req/10s vs baseline ${avgRate.toFixed(1)}. ${deviation.toFixed(1)}x deviation`,
    });
  } else if (deviation > 4) {
    await createAlert({
      userId, tokenHash,
      type: "RATE_ANOMALY",
      severity: "HIGH",
      reason: `Request spike: ${count} req/10s vs baseline ${avgRate.toFixed(1)}. ${deviation.toFixed(1)}x deviation`,
    });
  }

};

/* ------------------------------------------------ */
/* PRIVILEGE ABUSE                                  */
/* Non-admin on /api/admin → CRITICAL + revoke      */
/* Paper: supports detecting unauthorised access    */
/* ------------------------------------------------ */

export const detectPrivilegeAbuse = async ({ userId, tokenHash, endpoint, role }) => {

  if (endpoint?.startsWith("/api/admin") && role !== "admin") {
    await createAlert({
      userId, tokenHash,
      type: "PRIVILEGE_ABUSE",
      severity: "CRITICAL",
      reason: `Non-admin (role=${role}) attempted admin route: ${endpoint}`,
      actionTaken: "REVOKED",
    });

    await RevokedToken.updateOne(
      { tokenHash },
      { $setOnInsert: { tokenHash, reason: "Privilege abuse — non-admin on admin route" } },
      { upsert: true }
    );
  }

};

/* ------------------------------------------------ */
/* DEVICE ANOMALY                                   */
/* Browser-family matching (tolerates version bumps)*/
/* Paper Group 1/2 (Rules 2, 5 — user-agent change)*/
/* ------------------------------------------------ */

export const detectDeviceAnomaly = async ({ userId, tokenHash, userAgent }) => {

  if (!userAgent) return;

  const baseline     = await getUserBaseline(userId);
  const knownDevices = baseline?.knownDevices || [];

  if (knownDevices.length === 0) return;

  const parseBrowserFamily = (ua) => {
    if (!ua) return "";
    const m = ua.match(/(Chrome|Firefox|Safari|Edge|OPR|MSIE|Trident)[/\s][\d.]+/i);
    return m ? m[1].toLowerCase() : ua.toLowerCase().slice(0, 40);
  };

  const currentFamily = parseBrowserFamily(userAgent);
  const knownFamilies = knownDevices.map(parseBrowserFamily);

  if (!knownFamilies.includes(currentFamily)) {
    await createAlert({
      userId, tokenHash,
      type: "DEVICE_ANOMALY",
      severity: "MEDIUM",
      reason: `Unknown browser family: "${currentFamily}". Known: ${knownFamilies.slice(0, 3).join(", ")}`,
    });
  }

};

/* ------------------------------------------------ */
/* IP ANOMALY                                       */
/* Paper Group 1/2 (Rules 1, 4 — IP change)        */
/* ------------------------------------------------ */

export const detectIPAnomaly = async ({ userId, tokenHash, ipAddress }) => {

  if (!ipAddress) return;

  const baseline = await getUserBaseline(userId);
  const knownIPs = (baseline?.knownIPs || []).slice(-50);

  if (knownIPs.length === 0) return;

  if (!knownIPs.includes(ipAddress)) {
    await createAlert({
      userId, tokenHash,
      type: "IP_ANOMALY",
      severity: "MEDIUM",
      reason: `Access from unrecognised IP: ${ipAddress}. Recent known IPs: ${knownIPs.slice(-3).join(", ")}`,
    });
  }

};

/* ------------------------------------------------ */
/* ENDPOINT SCANNING                                */
/* Thresholds: >20 = CRITICAL, >10 = HIGH           */
/* Excludes baseline/static endpoints               */
/* ------------------------------------------------ */

const STATIC_ENDPOINTS = ["/", "/api/health", "/favicon.ico", "/api/user/profile"];

export const detectEndpointScanning = async ({ userId, tokenHash }) => {

  const rawEndpoints = await RequestLog.distinct("endpoint", {
    userId,
    createdAt: { $gte: new Date(Date.now() - 60000) }
  });

  const endpoints = rawEndpoints.filter(e => !STATIC_ENDPOINTS.includes(e));

  if (endpoints.length > 20) {
    await createAlert({
      userId, tokenHash,
      type: "API_SCAN",
      severity: "CRITICAL",
      reason: `Aggressive scanning: ${endpoints.length} unique endpoints/60s`,
    });
  } else if (endpoints.length > 10) {
    await createAlert({
      userId, tokenHash,
      type: "API_SCAN",
      severity: "HIGH",
      reason: `Elevated scanning: ${endpoints.length} unique endpoints/60s`,
    });
  }

};

/* ------------------------------------------------ */
/* REVOKED TOKEN USE                                */
/* Double-guard — verifyJWT already blocks these,   */
/* but this ensures audit trail completeness        */
/* ------------------------------------------------ */

export const detectRevokedTokenUsage = async ({ userId, tokenHash }) => {

  const revoked = await RevokedToken.findOne({ tokenHash });

  if (revoked) {
    await createAlert({
      userId, tokenHash,
      type: "REVOKED_TOKEN_USE",
      severity: "CRITICAL",
      reason: `Revoked token reused. Original reason: "${revoked.reason}"`,
      actionTaken: "REVOKED",
    });
  }

};

/* ------------------------------------------------ */
/* LOGIN TIME ANOMALY                               */
/* ±1 hour tolerance. Needs ≥5 baseline hours.      */
/* ------------------------------------------------ */

export const detectLoginTimeAnomaly = async ({ userId, tokenHash }) => {

  const baseline    = await getUserBaseline(userId);
  const usualHours  = baseline?.usualLoginHours || [];

  if (usualHours.length < 5) return;

  const hour = new Date().getHours();
  const isUsualTime = usualHours.some(
    h => Math.abs(h - hour) <= 1 || Math.abs(h - hour) === 23
  );

  if (!isUsualTime) {
    await createAlert({
      userId, tokenHash,
      type: "LOGIN_TIME_ANOMALY",
      severity: "LOW",
      reason: `Activity at hour ${hour}:00 outside usual pattern. Known hours: [${usualHours.sort((a, b) => a - b).join(", ")}]`,
    });
  }

};

/* ------------------------------------------------ */
/* TOKEN LIFETIME ABUSE                             */
/* Configurable via TOKEN_MAX_AGE_MS env var.        */
/* Default: 12h. Exceeding = HIGH + auto-revoke.    */
/* ------------------------------------------------ */

export const detectTokenLifetimeAbuse = async ({ userId, tokenHash }) => {

  const firstLog = await RequestLog.findOne({ tokenHash }).sort({ createdAt: 1 });

  if (!firstLog) return;

  const tokenAgeMs = Date.now() - new Date(firstLog.createdAt).getTime();
  const maxAgeMs   = parseInt(process.env.TOKEN_MAX_AGE_MS || String(12 * 60 * 60 * 1000));

  if (tokenAgeMs > maxAgeMs) {
    const ageHours = (tokenAgeMs / 3600000).toFixed(1);
    await createAlert({
      userId, tokenHash,
      type: "TOKEN_LIFETIME_ABUSE",
      severity: "HIGH",
      reason: `Token active ${ageHours}h — exceeds max ${maxAgeMs / 3600000}h policy`,
      actionTaken: "REVOKED",
    });

    await RevokedToken.updateOne(
      { tokenHash },
      { $setOnInsert: { tokenHash, reason: `Token exceeded max lifetime (${ageHours}h)` } },
      { upsert: true }
    );
  }

};

/* ------------------------------------------------ */
/* IMPOSSIBLE TRAVEL                                */
/* Haversine distance. Scoped to same tokenHash.    */
/* FIX: was querying any-user prev IP — now scoped  */
/* to same token to prevent false positives on      */
/* legitimate multi-session users.                  */
/* Speed > 900 km/h within 10 min = CRITICAL.       */
/* ------------------------------------------------ */

export const detectImpossibleTravel = async ({ userId, tokenHash, ipAddress }) => {

  if (!ipAddress) return;

  // Scope to same token — prevents false-positive from prior sessions
  const lastLog = await RequestLog.findOne({
    tokenHash,
    ipAddress: { $ne: ipAddress },
  }).sort({ createdAt: -1 });

  if (!lastLog || !lastLog.ipAddress) return;

  const distance  = geoDistance(lastLog.ipAddress, ipAddress);
  const timeDiffMs = Date.now() - new Date(lastLog.createdAt).getTime();

  if (distance === 0) return; // private IPs or unknown geo

  const speedKmh = distance / (timeDiffMs / 3600000);

  // Only alert if travel is physically impossible AND recent (within 10 min)
  if (speedKmh > 900 && timeDiffMs < 600000) {
    await createAlert({
      userId, tokenHash,
      type: "IMPOSSIBLE_TRAVEL",
      severity: "CRITICAL",
      reason: `Impossible travel: ${distance.toFixed(0)}km in ${(timeDiffMs / 60000).toFixed(1)}min (${speedKmh.toFixed(0)} km/h). ${lastLog.ipAddress} → ${ipAddress}`,
      actionTaken: "REVOKED",
    });

    await RevokedToken.updateOne(
      { tokenHash },
      { $setOnInsert: { tokenHash, reason: "Impossible travel — session terminated" } },
      { upsert: true }
    );
  }

};

/* ------------------------------------------------ */
/* INVALID TOKEN FLOOD                              */
/* Tiered: >25 = CRITICAL, >10 = HIGH              */
/* Per-IP, not per-user (attacker may be anonymous) */
/* ------------------------------------------------ */

export const detectInvalidTokenFlood = async ({ userId, tokenHash, ipAddress }) => {

  if (!ipAddress) return;

  const attempts = await RequestLog.countDocuments({
    ipAddress,
    tokenValid: false,
    createdAt: { $gte: new Date(Date.now() - 60000) }
  });

  if (attempts > 25) {
    await createAlert({
      userId: userId || null,
      tokenHash: tokenHash || `ip-flood-${ipAddress}`,
      type: "INVALID_TOKEN_FLOOD",
      severity: "CRITICAL",
      reason: `Brute-force flood: ${attempts} invalid tokens from ${ipAddress} in 60s`,
    });
  } else if (attempts > 10) {
    await createAlert({
      userId: userId || null,
      tokenHash: tokenHash || `ip-flood-${ipAddress}`,
      type: "INVALID_TOKEN_FLOOD",
      severity: "HIGH",
      reason: `Elevated invalid attempts: ${attempts} from ${ipAddress} in 60s`,
    });
  }

};

/* ------------------------------------------------ */
/* BEHAVIOR ANOMALY (signature-based)               */
/* Volume + bot timing regularity (stdDev < 50ms)  */
/* ML anomaly is handled separately in detectMLAnomaly */
/* ------------------------------------------------ */

export const detectBehaviorAnomaly = async ({ userId, tokenHash }) => {

  const baseline = await getUserBaseline(userId);
  const avgRate  = Math.max(baseline?.avgRate || 1, 5);

  const recentLogs = await RequestLog.find({
    userId,
    createdAt: { $gte: new Date(Date.now() - 60000) }
  }).select("createdAt endpoint").sort({ createdAt: 1 }).lean();

  const count = recentLogs.length;

  // Volume check
  if (count > avgRate * 6) {
    await createAlert({
      userId, tokenHash,
      type: "BEHAVIOR_ANOMALY",
      severity: "HIGH",
      reason: `Volume anomaly: ${count} req/min vs baseline ${avgRate.toFixed(1)}/s. Ratio: ${(count / avgRate).toFixed(1)}x`,
    });
    return;
  }

  // Bot timing regularity check
  if (recentLogs.length >= 10) {
    const intervals = [];
    for (let i = 1; i < recentLogs.length; i++) {
      intervals.push(
        new Date(recentLogs[i].createdAt).getTime() -
        new Date(recentLogs[i - 1].createdAt).getTime()
      );
    }
    const avgInterval = intervals.reduce((a, b) => a + b, 0) / intervals.length;
    const variance    = intervals.reduce((a, b) => a + Math.pow(b - avgInterval, 2), 0) / intervals.length;
    const stdDev      = Math.sqrt(variance);

    if (stdDev < 50 && count >= 10) {
      await createAlert({
        userId, tokenHash,
        type: "BEHAVIOR_ANOMALY",
        severity: "CRITICAL",
        reason: `Bot-like timing: ${count} requests with ${stdDev.toFixed(1)}ms interval stdDev (near-perfect regularity)`,
      });
    }
  }

};

/* ------------------------------------------------ */
/* CONCURRENT SESSION DETECTION                     */
/* >3 active tokens in 15 min for same user = HIGH  */
/* Paper Groups 4–6 (Rules 13–21)                   */
/* ------------------------------------------------ */

export const detectConcurrentSessions = async ({ userId, tokenHash }) => {

  if (!userId) return;

  const recentHashes = await RequestLog.distinct("tokenHash", {
    userId,
    tokenHash: { $ne: null },
    createdAt: { $gte: new Date(Date.now() - 900000) }
  });

  const activeTokens = recentHashes.filter(Boolean);

  if (activeTokens.length > 3) {
    await createAlert({
      userId, tokenHash,
      type: "CONCURRENT_SESSION",
      severity: "HIGH",
      reason: `${activeTokens.length} concurrent active tokens for this user in 15 min`,
    });
  }

};

/* ------------------------------------------------ */
/* SECURITY PIPELINE — TIERED PARALLEL EXECUTION   */
/*                                                  */
/* Tier 1 (serial):   cheapest + most critical      */
/* Tier 2 (parallel): medium cost                   */
/* Tier 3 (parallel): baseline-dependent            */
/* Tier 4 (parallel): ML + expensive geo            */
/* ------------------------------------------------ */

export const runSecurityChecks = async (context) => {

  // Set module-level arrival time so createAlert can measure latency for every alert
  _currentRequestArrivalTime = context.requestArrivalTime || null;

  // Tier 1: cheapest, most critical — serial to short-circuit fast
  await detectRevokedTokenUsage(context);
  await detectPrivilegeAbuse(context);
  await detectForgery(context);            // Rule 25 — check issuance registry

  // Tier 2: medium cost — parallel
  await Promise.all([
    detectTokenReplay(context),
    detectInvalidTokenFlood(context),
    detectConcurrentSessions(context),
  ]);

  // Tier 3: baseline-dependent — parallel
  await Promise.all([
    detectRateAnomaly(context),
    detectBehaviorAnomaly(context),
    detectDeviceAnomaly(context),
    detectIPAnomaly(context),
    detectEndpointScanning(context),
    detectLoginTimeAnomaly(context),
    detectTokenLifetimeAbuse(context),
  ]);

  // Tier 4: expensive — geo + ML in parallel (ML is async DB + compute)
  await Promise.all([
    detectImpossibleTravel(context),
    detectMLAnomaly(context),             // Isolation Forest scoring
  ]);

};
